=== liquidaty/sxupdate/schema/appcast.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "JSON schema for use with sxupdate library, used to hold metadata for version updates",
  "required": [
    "items"
  ],
  "type": "object",
  "properties": {
    "comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "language": {
      "type": "string"
    },
    "items": {
      "type": "array",
      "minItems": 1,
      "items": [
        {
          "type": "object",
          "properties": {
            "version": {
              "description": "Representation of semantic version. See https://semver.org/",
              "type": "object",
              "required": [ "major", "minor", "patch" ],
              "properties": {
                "major": { "type": "integer" },
                "minor": { "type": "integer" },
                "patch": { "type": "integer" },
                "prerelease": {
                  "description": "Non-blank string consisting of one or more non-blank identifiers, each one of more chars in the range [0-9A-Za-z-]",
                  "type": "string"
                },
                "meta": {
                  "type": "string"
                }
              }
            },
            "enclosure": {
              "type": "object",
              "properties": {
                "url": {
                  "description": "Must be of the form https://... (fetch from URL), file://... (local file), or a local file path, relative to the URL where this JSON document is located, containing no colon or backslash character",
                  "pattern": "^(((https|file)://[^/].*)|[^:\\\\]+)$",
                  "type": "string"
                },
                "length": {
                  "type": "integer"
                },
                "filename": {
                  "description": "Name of the file that will be downloaded. May only contain alphanumeric characters, slash, dash, underscore and period, may not contain two slashes in a row, and may not end with a slash",
                  "pattern": "^/?([-_A-Za-z0-9.]+/?)*[-_A-Za-z0-9.]$",
                  "type": "string"
                },
                "signature": {
                  "type": "string"
                }
              },
              "required": [
                "url",
                "length",
                "filename",
                "signature"
              ]
            }
          },
          "required": [
            "version",
            "enclosure"
          ]
        }
      ]
    }
  }
}

=== liquidaty/sxupdate/test/example1/appcast.json
{
  "comment": "test/example1 appcast configuration",
  "title": "Example / Test1 Change Log",
  "link": "https://github.com/liquidaty/sxupdate/blob/main/test/example1/appcast.json",
  "description": "Most recent changes with links to updates",
  "language": "en",
  "items": [
    {
      "title": "Version 1.0.0",
      "link": "https://github.com/liquidaty/sxupdate",
      "version": {
        "major": 1,
        "minor": 0,
        "patch": 0,
        "prerelease": "alpha",
        "meta": "21AF26D3"
      },
      "description": "This is version 1.0.0-alpha+21AF26D3. Version info must follow Semantic Versioning as described at https://semver.org",
      "pubDate": "Wed, 10 May 2023 14:08:38 +0700",
      "enclosure": {
        "url": "https://github.com/liquidaty/sxupdate/blob/main/test/example1/test_installer.exe",
        "length": 99999,
        "type": "application/octet-stream",
        "sxupdate:edSignature": "XXXXXXX"
      }
    }
  ]
}

=== liquidaty/sxupdate/examples/appcast.json
{
  "comment": "converted to json from https://sparkle-project.org/files/sparkletestcast.xml",
  "title": "Sparkle Test App Changelog",
  "link": "http://sparkle-project.org/files/sparkletestcast.xml",
  "description": "Most recent changes with links to updates.",
  "language": "en",
  "items": [
    {
      "title": "Version 2.0",
      "link": "https://sparkle-project.org",
      "version": 2,
      "description": "<ul> <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li> <li>Suspendisse sed felis ac ante ultrices rhoncus. Etiam quis elit vel nibh placerat facilisis in id leo.</li> <li>Vestibulum nec tortor odio, nec malesuada libero. Cras vel convallis nunc.</li> <li>Suspendisse tristique massa eget velit consequat tincidunt. Praesent sodales hendrerit pretium.</li> </ul> ",
      "pubDate": "Sat, 26 Jul 2014 15:20:11 +0000",
      "enclosure": {
        "url": "https://sparkle-project.org/files/Sparkle%20Test%20App.zip",
        "length": 107758,
        "type": "application/octet-stream",
        "simpleXUpdate:edSignature": "7cLALFUHSwvEJWSkV8aMreoBe4fhRa4FncC5NoThKxwThL6FDR7hTiPJh1fo2uagnPogisnQsgFgq6mGkt2RBw=="
      }
    }
  ]
}
